// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SyZero.Infrastructure.EntityFramework;

namespace SyZero.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(SyDbContext))]
    [Migration("20181222163806_test2.2.1")]
    partial class test221
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SyZero.Domain.Model.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Author")
                        .HasMaxLength(200);

                    b.Property<string>("Content");

                    b.Property<int>("Ctid");

                    b.Property<int>("Hot");

                    b.Property<string>("Img")
                        .HasMaxLength(200);

                    b.Property<int>("IsDisplay");

                    b.Property<string>("L01");

                    b.Property<string>("L02");

                    b.Property<string>("L03");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Article");
                });

            modelBuilder.Entity("SyZero.Domain.Model.Categorys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Parentid");

                    b.HasKey("Id");

                    b.ToTable("Categorys");
                });

            modelBuilder.Entity("SyZero.Domain.Model.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<int>("Artid");

                    b.Property<string>("Content")
                        .HasMaxLength(1000);

                    b.Property<string>("L01");

                    b.Property<string>("L02");

                    b.Property<string>("L03");

                    b.Property<int>("Pabulous");

                    b.Property<int>("Parent");

                    b.Property<int>("Userid");

                    b.HasKey("Id");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("SyZero.Domain.Model.Configure", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasMaxLength(200);

                    b.Property<string>("Content")
                        .HasMaxLength(1000);

                    b.Property<string>("L01");

                    b.Property<string>("L02");

                    b.Property<string>("L03");

                    b.Property<string>("Other")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("Configure");
                });

            modelBuilder.Entity("SyZero.Domain.Model.FriendLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Category")
                        .HasMaxLength(200);

                    b.Property<string>("Href")
                        .HasMaxLength(1000);

                    b.Property<string>("L01");

                    b.Property<string>("L02");

                    b.Property<string>("L03");

                    b.Property<string>("Title")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("FriendLin");
                });

            modelBuilder.Entity("SyZero.Domain.Model.Messaged", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Content")
                        .HasMaxLength(1000);

                    b.Property<string>("L01");

                    b.Property<string>("L02");

                    b.Property<string>("L03");

                    b.Property<int>("Parent");

                    b.Property<int>("Userid");

                    b.HasKey("Id");

                    b.ToTable("Messaged");
                });

            modelBuilder.Entity("SyZero.Domain.Model.Seo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Artid");

                    b.Property<string>("Describe")
                        .HasMaxLength(200);

                    b.Property<string>("Keyword")
                        .HasMaxLength(200);

                    b.Property<string>("L01");

                    b.Property<string>("L02");

                    b.Property<string>("L03");

                    b.HasKey("Id");

                    b.ToTable("Seo");
                });

            modelBuilder.Entity("SyZero.Domain.Model.TimeAxis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Brief")
                        .HasMaxLength(200);

                    b.Property<DateTime>("Releasetime");

                    b.Property<string>("Releasetitle")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("TimeAxis");
                });

            modelBuilder.Entity("SyZero.Domain.Model.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Ctid");

                    b.Property<string>("L01");

                    b.Property<string>("L02");

                    b.Property<string>("L03");

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<string>("Tqm")
                        .HasMaxLength(200);

                    b.Property<string>("Url")
                        .HasMaxLength(1000);

                    b.HasKey("Id");

                    b.ToTable("Tool");
                });

            modelBuilder.Entity("SyZero.Domain.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AddTime");

                    b.Property<string>("Headimg")
                        .HasMaxLength(1000);

                    b.Property<string>("L01");

                    b.Property<string>("L02");

                    b.Property<string>("L03");

                    b.Property<DateTime>("LastTime");

                    b.Property<string>("Mail")
                        .HasMaxLength(200);

                    b.Property<string>("Name")
                        .HasMaxLength(200);

                    b.Property<string>("Paw")
                        .HasMaxLength(200);

                    b.Property<string>("Phone")
                        .HasMaxLength(200);

                    b.Property<string>("Sex")
                        .HasMaxLength(200);

                    b.Property<int>("State");

                    b.Property<int>("Utype");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("SyZero.Domain.Model.UserType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Authority")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.ToTable("UserType");
                });
#pragma warning restore 612, 618
        }
    }
}
